homeassistant:
    name: Home
    customize: !include customize.yaml
    latitude: !secret latitude
    longitude: !secret longitude
    # Impacts weather/sunrise data (altitude above sea level in meters)
    elevation: 186
    # metric for Metric, imperial for Imperial
    unit_system: imperial
    # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
    time_zone: America/Chicago

    # https://github.com/andrey-git/home-assistant-custom-ui
    customize_glob:
        light.*:
            custom_ui_state_card: custom_light

# Show links to resources in log and frontend
# introduction:

# Enables the frontend
frontend:

# Enables configuration UI
config:

http:
    api_password: !secret api_password
#    base_url: !secret host

# Checks for available updates
updater:

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time.
history:

# View all events in a logbook
logbook:

# Track the sun
sun:

recorder:
    db_url: !secret db_url

# Text to speech
tts:
    platform: google

group: !include groups.yaml

nest:
    client_id: !secret nest_id
    client_secret: !secret nest_secret

google:
    client_id: !secret google_id
    client_secret: !secret google_secret

zwave:
    usb_path: /dev/ttyACM0
    config_path: /srv/homeassistant/src/python-openzwave/openzwave/config
    polling_interval: 60000
    # debug: 1
    # autoheal: False
    device_config: !include zwave_device_config.yaml

wink:
    email: !secret wink_email
    password: !secret wink_password
#    access_token: !secret wink_token
#    refresh_token: !secret wink_refresh
#    client_id: !secret wink_client_id
#    client_secret: !secret wink_client_secret

mqtt:
    broker: 192.168.1.4
    port: 1883
    keepalive: 60
    client_id: homeassistant
    username: !secret mqtt_username
    password: !secret mqtt_password
    protocol: 3.1

cover:
    - platform: myq
      username: !secret myq_username
      password: !secret myq_password
      type: chamberlain

notify:
    - name: pushbullet
      platform: pushbullet
      api_key: !secret pushbullet_key

media_player:
    - platform: spotify
      client_id: !secret spotify_id
      client_secret: !secret spotify_secret

device_tracker: !include device_tracker.yaml
input_select: !include input_select.yaml
input_boolean: !include input_boolean.yaml
input_slider: !include input_slider.yaml
sensor: !include sensor.yaml
automation: !include_dir_merge_list automation
