light.kitchen_level_4_0:
  refresh_value: true
  delay: 2
  polling_intensity: 1
light.dining_room_level_5_0:
  refresh_value: true
  delay: 2
  polling_intensity: 1
zwave.kwikset_touchpad_electronic_deadbolt_9:
  ignored: false
  polling_intensity: 1
