
    # https://community.home-assistant.io/t/z-wave-devices-stop-reporting-to-hass/6636/28
    light.ge_12724_3way_dimmer_switch_level_4_0:
        refresh_value: true   # refresh the brightness value if the dimmer do "soft off"
        delay: 2              # Amount of seconds before the refresh is done after the actual action.
        polling_intensity: 1  # Polls the device when each (polling_intensity) polling is performed(By polling_interval)
    
    light.ge_12724_3way_dimmer_switch_level_5_0:
        refresh_value: true   # refresh the brightness value if the dimmer do "soft off"
        delay: 2              # Amount of seconds before the refresh is done after the actual action.
        polling_intensity: 1  # Polls the device when each (polling_intensity) polling is performed(By polling_interval)

