light.kitchen_level_4_0:
  refresh_value: true
  delay: 2
  polling_intensity: 0
  ignored: false
light.dining_room_level_5_0:
  refresh_value: true
  delay: 2
  polling_intensity: 0
  ignored: false
zwave.kwikset_touchpad_electronic_deadbolt_9:
  ignored: false
  polling_intensity: 1
light.front_porch_level_11_0:
  ignored: false
  polling_intensity: 0
light.living_room_level_10_0:
  ignored: false
  polling_intensity: 0
light.garage_level_12_0:
  ignored: false
  polling_intensity: 0
light.master_bedroom_level_14_0:
  ignored: false
  polling_intensity: 0
