- platform: template
  sensors:
      battery_motion_living_room:
          value_template: '{{ states.zwave.living_room_2.attributes.battery_level }}'
          friendly_name: 'Living Room Sensor Battery Level'
          unit_of_measurement: '%'

- platform: template
  sensors:
      battery_motion_dining_room:
          value_template: '{{ states.zwave.dining_room_2.attributes.battery_level }}'
          friendly_name: 'Dining Room Sensor Battery Level'
          unit_of_measurement: '%'

- platform: template
  sensors:
      battery_motion_kitchen:
          value_template: '{{ states.zwave.kitchen_2.attributes.battery_level }}'
          friendly_name: 'Kitchen Sensor Battery Level'
          unit_of_measurement: '%'

- platform: template
  sensors:
      battery_lock_rear:
          value_template: '{{ states.zwave.kwikset_touchpad_electronic_deadbolt.attributes.battery_level }}'
          friendly_name: 'Back Door Lock Battery Level'
          unit_of_measurement: '%'